// <auto-generated />
using System;
using AECS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AECS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AecsDbContext))]
    partial class AecsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AECS.Domain.Models.EvidenceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TaskId");

                    b.ToTable("EvidenceEvents");
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.ExecutionEvidenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChainSealJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer");

                    b.Property<string>("EvidenceContentHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EvidenceSealJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId")
                        .IsUnique();

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TaskId");

                    b.ToTable("execution_evidence", null, t =>
                        {
                            t.HasCheckConstraint("ck_execution_evidence_event_count", "\"EventCount\" >= 0");

                            t.HasCheckConstraint("ck_execution_evidence_schema_version", "\"SchemaVersion\" = 'aecs.execution-evidence/v1'");
                        });
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.ExperimentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cpvc")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FirstPassRate")
                        .HasColumnType("double precision");

                    b.Property<int>("HumanReviewCount")
                        .HasColumnType("integer");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<TimeSpan>("TotalDuration")
                        .HasColumnType("interval");

                    b.Property<int>("TotalTasks")
                        .HasColumnType("integer");

                    b.Property<int>("VerifiedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.ToTable("ExperimentRuns");
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.HistoricalDecisionStorageRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Enforcement")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id", "Version");

                    b.HasIndex("ReviewStatus");

                    b.HasIndex("Source");

                    b.HasIndex("ValidUntil");

                    b.ToTable("historical_decisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_historical_decisions_schema_version", "\"SchemaVersion\" = 'aecs.historical-decision/v1'");

                            t.HasCheckConstraint("ck_historical_decisions_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.HistoricalDecisionSuppressionStorageRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DecisionVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SuppressionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id", "Version");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("DecisionId", "DecisionVersion");

                    b.ToTable("historical_decision_suppressions", null, t =>
                        {
                            t.HasCheckConstraint("ck_historical_decision_suppressions_schema_version", "\"SchemaVersion\" = 'aecs.historical-decision-suppression/v1'");

                            t.HasCheckConstraint("ck_historical_decision_suppressions_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.PromotionEvidenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExecutionEvidenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SealJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SignedAt");

                    b.HasIndex("ExecutionEvidenceId", "Sequence")
                        .IsUnique();

                    b.ToTable("execution_evidence_promotion_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_execution_evidence_promotion_sequence", "\"Sequence\" > 0");
                        });
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.ReplayEvidenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExecutionEvidenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReplayJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SealJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SignedAt");

                    b.HasIndex("ExecutionEvidenceId", "Sequence")
                        .IsUnique();

                    b.ToTable("execution_evidence_replay_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_execution_evidence_replay_sequence", "\"Sequence\" > 0");
                        });
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.HistoricalDecisionSuppressionStorageRecord", b =>
                {
                    b.HasOne("AECS.Infrastructure.Persistence.HistoricalDecisionStorageRecord", null)
                        .WithMany()
                        .HasForeignKey("DecisionId", "DecisionVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.PromotionEvidenceRecord", b =>
                {
                    b.HasOne("AECS.Infrastructure.Persistence.ExecutionEvidenceRecord", "ExecutionEvidence")
                        .WithMany("PromotionEvents")
                        .HasForeignKey("ExecutionEvidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionEvidence");
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.ReplayEvidenceRecord", b =>
                {
                    b.HasOne("AECS.Infrastructure.Persistence.ExecutionEvidenceRecord", "ExecutionEvidence")
                        .WithMany("ReplayEvents")
                        .HasForeignKey("ExecutionEvidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionEvidence");
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.ExecutionEvidenceRecord", b =>
                {
                    b.Navigation("PromotionEvents");

                    b.Navigation("ReplayEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
