// <auto-generated />
using System;
using AECS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AECS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AecsDbContext))]
    partial class AecsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AECS.Domain.Models.EvidenceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TaskId");

                    b.ToTable("EvidenceEvents");
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.ExecutionEvidenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChainSealJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceContentHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EvidenceSealJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PromotionCount")
                        .HasColumnType("integer");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId")
                        .IsUnique();

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TaskId");

                    b.ToTable("execution_evidence", null, t =>
                        {
                            t.HasCheckConstraint("ck_execution_evidence_promotion_count", "\"PromotionCount\" >= 0");

                            t.HasCheckConstraint("ck_execution_evidence_schema_version", "\"SchemaVersion\" = 'aecs.execution-evidence/v1'");
                        });
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.ExperimentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cpvc")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FirstPassRate")
                        .HasColumnType("double precision");

                    b.Property<int>("HumanReviewCount")
                        .HasColumnType("integer");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<TimeSpan>("TotalDuration")
                        .HasColumnType("interval");

                    b.Property<int>("TotalTasks")
                        .HasColumnType("integer");

                    b.Property<int>("VerifiedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.ToTable("ExperimentRuns");
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.PromotionEvidenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExecutionEvidenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SealJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SignedAt");

                    b.HasIndex("ExecutionEvidenceId", "Sequence")
                        .IsUnique();

                    b.ToTable("execution_evidence_promotion_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_execution_evidence_promotion_sequence", "\"Sequence\" > 0");
                        });
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.PromotionEvidenceRecord", b =>
                {
                    b.HasOne("AECS.Infrastructure.Persistence.ExecutionEvidenceRecord", "ExecutionEvidence")
                        .WithMany("PromotionEvents")
                        .HasForeignKey("ExecutionEvidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionEvidence");
                });

            modelBuilder.Entity("AECS.Infrastructure.Persistence.ExecutionEvidenceRecord", b =>
                {
                    b.Navigation("PromotionEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
